### ISSUE TITLE
Add more info for the purgeCSS part

### ISSUE THREAD

**Issue by willdante** [nuxt-community/nuxt-tailwindcss#15]
Hi,
Thanks for this great module.

If I'm right, we need to install nuxt-purgecss in addition to tailwindcss module.
Maybe it should be indicated in the documentation.

I'd also like to know what is the default purgecss configuration and if I can tweak it like I would do when installing tailwind css and nuxt-purgecss.

Thanks in advance.

**Comment by lukio3** [comment]
I am also wondering how to change the whitelist for my purgecss config. I can't see where the purgecss configs are?

**Comment by lukio3** [comment]
Ok got it (for anyone who finds themselves here),

within your nuxt.config.js file you can add a purgeCSS config object,

for example:

```
  /*
  ** Purgecss configuration
  */
  purgeCSS: {
    whitelist: ['example-dynamic-css-selector']
  },
```
