### ISSUE TITLE
Theme extend in tailwind config file renders syntax error

### ISSUE THREAD

**Issue by sbkl** [nuxt-community/nuxt-tailwindcss#16]
Hi,

When extending the theme for spacing for instance, Nuxt.js render a syntax error (pointing spacing in my config file below).

Could you please check if this is a bug?

No problem if I totally override the default theme.

My tailwind.config.js file below following tailwind documentation:
```
module.exports = {
  theme: {
      extend: {
        spacing: {
            'test': '24rem'
        }
      },
  },
  variants: {},
  plugins: []
}
```
Thank you.
Best regards,
Sebastien

**Comment by Atinux** [comment]
Hey @sbkl 

Do you mind forking https://codesandbox.io/s/o4vn5pvp7q and creating a reproduction please?

**Comment by sbkl** [comment]
Thanks @Atinux 
I've updated to version 1.1.1 just like your sandbox and it is now working. The bug was happening in v1.1.0.
