### ISSUE TITLE
Custom style with module

### ISSUE THREAD

**Issue by kalicki** [nuxt-community/nuxt-tailwindcss#17]
Guys, 

I detected a strange factor... In my use case I would like to stash with `@apply` some classes of `tailwind`, however, the way it is done today it loads so that I can not have a custom file applying other styles.

### 1 - E.g.:
```ts
# nuxt.config.js
css: ['~/assets/css/tailwind.css', '~/assets/css/app.css'],

...

build: {
      postcss: {
            plugins: {
                  tailwindcss: './tailwind.config.js',
            }
      }
}
```

```css
# assets/css/app.css
@import "./components/_button";

input.form__control:focus,
select.form__control:focus,
textarea.form__control:focus {
    @apply .border-blue-500;
}
```

```css
# assets/css/components/_button.css 
.bt {
    @apply .bg-blue-500
}
```

The above case allows me to use an extra file to customize my style. But only with the case below I can not use an extra file (e.g: app.css)

### 2 - E.g:
```ts
# nuxt.config.js
css: ['~/assets/css/app.css'],

devModules: ['@nuxtjs/tailwindcss'],
```

`npm run dev` => this works perfectly (eg1 and eg2)
`npm run generate` => here it gives problem, the custom style is not indexed follow eg2 (only works with eg1)

**Comment by Atinux** [comment]
Hey @kalicki 

Do you mind forking https://codesandbox.io/s/o4vn5pvp7q and creating a reproduction please?
