### ISSUE TITLE
disable creation of tailwind.css file

### ISSUE THREAD

**Issue by pschaub** [nuxt-community/nuxt-tailwindcss#19]
In my project I include tailwind through a scss file. Is there a way to disable the creation of the css file?

**assets/scss/tailwind.scss**
```
@tailwind base;

@tailwind components;

@tailwind utilities;
```
see https://tailwindcss.com/docs/using-with-preprocessors/

**Comment by Atinux** [comment]
Hi @pschaub, sorry for the late answer (my GitHub notifications are shit).

Actually you can give a `scss` path for the `cssPath` key, example: `cssPath: '~/assets/scss/tailwind.scss'`

Then you may want to change the import to use '~' in front of `tailwind`:

`assets/scss/tailwind.scss`:
```scss
@import '~tailwindcss/base';
@import '~tailwindcss/components';
@import '~tailwindcss/utilities';
```

Demo: https://codesandbox.io/s/nuxt-tailwindcss-l3d5j
