### ISSUE TITLE
hide postcss-preset-env stage information

### ISSUE THREAD

**Issue by pschaub** [nuxt-community/nuxt-tailwindcss#20]
if i run `nuxt dev` it will show the following information:

> postcss-preset-env stage is set to 1 for supporting advanced css features

is it possible to hide this? I think our developers don't need to see this information every time.

**Comment by Atinux** [comment]
Hey @pschaub 

I guess we can remove this log directly, if you want to do your first PR please go ahead :)

**Comment by Atinux** [comment]
Fixed in [v1.1.2](https://github.com/nuxt-community/nuxt-tailwindcss/releases/tag/v1.1.2)
