### ISSUE TITLE
Nested css class won't work

### ISSUE THREAD

**Issue by na86** [nuxt-community/nuxt-tailwindcss#28]
Hi there, 

thanks for your extraordinary work with nuxt (and all the other stuff :D)

I've encountered this very strange issue. 
In all my css files nested class won't work. 
I didn't change anything from the default conf.

Anyone knows why? 

Thank you guys!

**Comment by Atinux** [comment]
Hi @na86 

Could you please provide and example of your nested CSS classes?

**Comment by na86** [comment]
Hi @Atinux 

here's a sandbox

[https://codesandbox.io/s/nuxt-tailwindcss-nd7v2?fontsize=14](url)

i hope is clear enough...

thank you (i'm a huge  fan of your work!)

**Comment by manniL** [comment]
You forgot the ampersand :relaxed: 	(more info in the [specs](https://tabatkins.github.io/specs/css-nesting/))

```postcss
.tile {
  @apply rounded-full bg-green-700 w-64 h-64 relative;
  & .tile-content {
    @apply rounded-full bg-white w-32 h-32 absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
}
```

**Comment by na86** [comment]
thank you @manniL, you're right i forgot the "&" in this example. But even if i put the ampersand in there.. it still doesn't work :( 

Any suggestion?! 
Thank you guys

[https://codesandbox.io/s/nested-class-sample-nd7v2?fontsize=14](https://codesandbox.io/s/nested-class-sample-nd7v2?fontsize=14)

**Comment by na86** [comment]
Thanks @manniL 
i totally missed the beautiful postcss.preset-env nuxt has built in...
endless gratitude for your work guys.
