### ISSUE TITLE
On Windows, cssPath is causing problems

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt-community/nuxt-tailwindcss#30]
This is why my `this.options.css` array looks like after the build hook:

```
[
  '~/assets/style/app.styl',
  'material-design-icons-iconfont/dist/material-design-icons.css',
  'vuetify/dist/vuetify.css',
  'C:\\Users\\martin\\git\\sicon\\apps\\siconBase\\assets\\css\\tailwind.css'
]
```

I also tried to remove the alias resolver in my test, but this did not help.
The way how tailwind is loaded via the module, does not work for me.
On Linux it works.

**Comment by Atinux** [comment]
Sadly I cannot test on Windows but if someone can confirm it would be really nice :)
