### ISSUE TITLE
PurgeCSS breaks on BEM like class names

### ISSUE THREAD

**Issue by Arthemis97** [nuxt-community/nuxt-tailwindcss#33]
I have problem with element-ui and purgecss. Dev mode works fine. and element-ui styles breaks after build.. any help?

**Comment by Jimmylet** [comment]
Hi Arthemis97, I have the same problem. Have you solved yours?

**Comment by Arthemis97** [comment]
https://github.com/nuxt-community/nuxt-tailwindcss/issues/25#issuecomment-519472429
