### ISSUE TITLE
PurgeCSS Whitelist doesn't seem to work with regex

### ISSUE THREAD

**Issue by nathanedwards** [nuxt-community/nuxt-tailwindcss#39]
On other non-nuxt webpack projects we've used Regular Expressions for our Purge, egin a `postcss.config.js` file:

```javascript
purgecss({
  ...
  whitelistPatterns: [
    /lazyloaded/,
    /lazyload/,
  ...
```

Which does work. It's possible I'm doing something wrong, but if I try a regex on `nuxt-tailwincss` 

Then...

```javascript
purgeCSS: {
	whitelist: [
		// Doesn't work:
		/icon/,
		// Does work:
		'icon',
	],
},
```

Regex matching would be useful. Part of the reason you have whitelist in Purge will be for some programmatically generated classes, possibly looping through config, where you just want to whitelist to a pattern rather than explicit class names.

Thanks!

**Comment by Atinux** [comment]
Hi @nathanedwards 

Actually you have to use `whitelistPatterns` or `whitelistPatternsChildren` to use regular expressions, see more on https://www.purgecss.com/whitelisting#patterns

**Comment by toremato** [comment]
I encountered same issue: PurgeCSS removes transition classes. Here is the simplest config from `tailwind.config.js`:

```
purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      "components/**/*.vue",
      "layouts/**/*.vue",
      "pages/**/*.vue",
      "plugins/**/*.js",
      "nuxt.config.js"
    ],
    options: {
      whitelistPatterns: [ /-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/,  ],
    }
  }

```

which doesn't seem to work. Though I don't think there's a problem with regex as I've tried whitelisting them via special comments in my .scss file: 

```
/* purgecss ignore */
.page-enter-active, .page-leave-active {
    transition: opacity .3s;
}

/* purgecss ignore */
.page-enter, .page-leave {
    opacity: 0;
}
```
or

```
/* purgecss start ignore */

.page-enter-active, .page-leave-active {
    transition: opacity .3s;
}
.page-enter, .page-leave {
    opacity: 0;
}

/* purgecss end ignore */
```

and it doesn't work too
