### ISSUE TITLE
how to config tailwindcss with element UI (https://github.com/ElemeFE/element)

### ISSUE THREAD

**Issue by thinguyennam4059605** [nuxt-community/nuxt-tailwindcss#42]

**Comment by kennymark** [comment]
Combining tailwind and element ui in productions seems impossible. I have been trying to get it working for 2 weeks to no avail. works fine in dev but not production with nuxt generate.

**Comment by foxted** [comment]
I have it running fine in production, but you need to deactivate purgeCss in your `nuxt.config.js`:

```javascript
purgeCSS: {
        enabled: false,
    },
```

**Comment by hartmut-co-uk** [comment]
Instead of deactivating PurgeCSS entirely [whitelisting](https://purgecss.com/whitelisting.html#patterns) can be used as follows in `nuxt.config.js`:
```
  /*
  ** purgeCSS module configuration
  ** See https://github.com/Developmint/nuxt-purgecss#options
  */
  purgeCSS: {
    whitelistPatterns: [/^el-/],
  },
```

**Comment by foxted** [comment]
@hartmut-co-uk Not all classes in element is prefixed with `el` unfortunately :(

**Comment by hartmut-co-uk** [comment]
New tailwindcss v1.4 purge 🎉 🎈 comes to the rescue!!!
https://github.com/hartmut-co-uk/nuxt-tailwind14-element-example
Preveiw: https://hartmut-co-uk.github.io/nuxt-tailwind14-element-example/
