### ISSUE TITLE
How to work fine with vuetify

### ISSUE THREAD

**Issue by EryouHao** [nuxt-community/nuxt-tailwindcss#45]
I want to use tailwindcss + vuetify in nuxt, but the `nuxt-tailwindcss` will remove some vuetify class when build. 

Can you help me?

**Comment by EryouHao** [comment]
I add prefix `tw-` for tailwindcss and change the nuxt-purgecss config, then it works for me. thank you

**Comment by thinguyennam4059605** [comment]
Hi.
  purgeCSS: {
    whitelistPatterns: [/^v-*/, /^theme-*/, /^application--*/],
    whitelistPatternsChildren: [/^v-*/, /^theme-*/, /^application--*/],
    whitelist: ['spacer', 'primary', 'secondary', 'accent', 'error', 'warning', 'info', 'success']
  },
It's not working when build production
1. npm run build
2. npm run start
3. css will conflict
Could you help me?
@EryouHao

**Comment by thinguyennam4059605** [comment]
Hi @EryouHao 
Could you help me?
Thanks

**Comment by thinguyennam4059605** [comment]
hi
