### ISSUE TITLE
[Css conflicted] How to work fine with vuetify?

### ISSUE THREAD

**Issue by thinguyennam4059605** [nuxt-community/nuxt-tailwindcss#46]
Hi.
purgeCSS: {
whitelistPatterns: [/^v-/, /^theme-/, /^application--/],
whitelistPatternsChildren: [/^v-/, /^theme-/, /^application--/],
whitelist: ['spacer', 'primary', 'secondary', 'accent', 'error', 'warning', 'info', 'success']
},
It's not working when build production

npm run build
npm run start
css will conflict
Could you help me?
@EryouHao

**Comment by Atinux** [comment]
Actually I don’t recommend to use both Vuetify and Tailwind in your project
