### ISSUE TITLE
Documentation request in readme for lang="postcss"

### ISSUE THREAD

**Issue by RobotOptimist** [nuxt-community/nuxt-tailwindcss#49]
Will you please specify in the usage section that in order to use the @apply directive in pages / components you will need to set the lang="postcss"

```
<style lang="postcss">
  .h1 {
    @apply text-5xl text-green-600 font-semibold;
  }
</style>
```
Otherwise, the directive will not work. Thank you!

**Comment by Atinux** [comment]
Actually you don't need to set `lang="postcss"` in order to use `@apply`, see https://codesandbox.io/s/o4vn5pvp7q
