### ISSUE TITLE
Cannot find module '@nuxtjs/tailwindcss' - Deploy on Laravel Forge

### ISSUE THREAD

**Issue by sbkl** [nuxt-community/nuxt-tailwindcss#9]
Hi,

I'm trying to deploy my nuxt.js app on Laravel Forge and get the following error:

> Cannot find module '@nuxtjs/tailwindcss'

It's working well on my local machine.

Any idea what I'm missing?

Thank you.
Best regards,
Sebastien

**Comment by Atinux** [comment]
Hi,

Have you try to set it as dependencies instead of devDependenxies?

**Comment by sbkl** [comment]
Thanks Sebastien. That was the issue. Now working. Facing other issues related to pm2 to deploy nuxt using forge. If any resource you would recommend to follow for this, please let me know. That would be really helpful!

**Comment by adamwathan** [comment]
Seems like maybe the documentation should not recommend setting it as a devDependency if it's supposed to be a dependency to be able to deploy your site?

**Comment by gekkedev** [comment]
> Hi,
> 
> Have you try to set it as dependencies instead of devDependencies?

As @adamwathan aready asked, I want to emphase: Why would the recommended installation be a way that does not work in production?
Just in case, here is a PR: #190
